/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_viney_NativeExample */

#ifndef _Included_com_viney_NativeExample
#define _Included_com_viney_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_viney_NativeExample
 * Method:    addNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_viney_NativeExample_addNumbers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_viney_NativeExample
 * Method:    modifyPerson
 * Signature: (Lcom/viney/Person;)V
 */
JNIEXPORT void JNICALL Java_com_viney_NativeExample_modifyPerson
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
